# Basic Site Settings
locale                   : "en-GB"
site_theme               : "default"
title                    : "David J Poland"
title_separator          : "-"
name                     : &name "David J Poland"
description              : &description "Artificial intelligence and machine-learning researcher specialising in industrial predictive maintenance and machine prognostics."
url                      : "https://polandd.github.io"
baseurl                  : ""
repository               : "polandd/polandd.github.io"

# Site Author
author:
  avatar           : "profile.jpg"
  name             : "David J Poland"
  pronouns         :
  bio              : "AI and machine-learning researcher specialising in industrial predictive maintenance, machine prognostics and transformer-based systems."
  location         : "United Kingdom"
  employer         : "University of Hertfordshire"
  uri              :
  email            : "david.poland@hotmail.co.uk"

  # Academic profiles
  academia         :
  arxiv            : "https://arxiv.org/a/poland_d_2"
  googlescholar    : "https://scholar.google.co.uk/citations?user=Eyr5luEAAAAJ&hl=en"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0000-0002-0833-9338"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     : "https://www.researchgate.net/profile/David-Poland-5"
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "polandd"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
